name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Cog
      uses: replicate/setup-cog@v1.0.2
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}

    - name: Push to Replicate
      run: cog push r8.im/fire/tool-tortoise-text-to-speech
